services:
  mediapipe:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app     # live code sync
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload